# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9dd14210fe37b5f1dc2e4110b1910e34b595a8bdcf255480328f892f4159f371a805399e1127f5e59ad878ee83a74fb1145fcf87f52ce4351d79db5b485550e

test:
  secret_key_base: cf634f379a9a247ced3279593d176b0d963f19075836d867e392abffdec2746b73ee46fd228bf967515202466664dba39b3c5792df53aa924291a4ee89ba028a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
